services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - shithead

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    restart: unless-stopped
    volumes:
      - .:/app
      - go-modules:/go/pkg/mod
    expose:
      - 8080
    environment:
      APP_ENV: ${APP_ENV}
      PORT: ${PORT}
      MIGRATION_DIR: ${MIGRATION_DIR}
    networks:
      - shithead

  psql:
    image: postgres:13-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - shithead

volumes:
  go-modules:

networks:
  shithead:
    driver: bridge

